### Example 1: RandomUser API

##### We will use the get methods

In [1]:
# install the randomuser library
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5083 sha256=c1a68a7ca50c80f0e6aaf0376db47e2dc904ccd270ae4f946058b60660ae8e65
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/41/6f/23/878c103a235dc2d4e85a3965c124aae8a28470c541b81aa2ba
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [2]:
# load the necessary libraries
from randomuser import RandomUser
import pandas as pd

In [3]:
# create a random user object, r
r = RandomUser()

In [4]:
# get a list of random 10 users
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x7f0b5de77d00>,
 <randomuser.RandomUser at 0x7f0b5de77940>,
 <randomuser.RandomUser at 0x7f0b5de77340>,
 <randomuser.RandomUser at 0x7f0b5de77b80>,
 <randomuser.RandomUser at 0x7f0b5de77040>,
 <randomuser.RandomUser at 0x7f0b5de77580>,
 <randomuser.RandomUser at 0x7f0b5de7c7f0>,
 <randomuser.RandomUser at 0x7f0b5de7c970>,
 <randomuser.RandomUser at 0x7f0b5c441d90>,
 <randomuser.RandomUser at 0x7f0b5c441520>]

In [5]:
# get full names of the users and their email addresses using the get method
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Tracy Ellis   tracy.ellis@example.com
Chris Burton   chris.burton@example.com
Aada Kinnunen   aada.kinnunen@example.com
Mehmet Mayhoş   mehmet.mayhos@example.com
Peter Durand   peter.durand@example.com
Joel Wallace   joel.wallace@example.com
Felipe Cortes   felipe.cortes@example.com
Libaan Van Eenennaam   libaan.vaneenennaam@example.com
Januário Novaes   januario.novaes@example.com
Gérard Lecomte   gerard.lecomte@example.com

In [6]:
# generate photos of the random users.
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/73.jpg
https://randomuser.me/api/portraits/men/28.jpg
https://randomuser.me/api/portraits/women/28.jpg
https://randomuser.me/api/portraits/men/49.jpg
https://randomuser.me/api/portraits/men/97.jpg
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/8.jpg
https://randomuser.me/api/portraits/men/23.jpg
https://randomuser.me/api/portraits/men/52.jpg

In [7]:
# generate a table with information about the user e.g name, gender, city using the get methods
def get_users():
    users = []
    
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(), "Gender":user.get_gender(), "City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
        
    return pd.DataFrame(users)

In [8]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Emanuel Brevig,male,Vangsåsen,Møre og Romsdal,emanuel.brevig@example.com,1960-05-09T02:16:40.988Z,https://randomuser.me/api/portraits/men/88.jpg
1,Nuria Moreno,female,Pozuelo de Alarcón,Comunidad de Madrid,nuria.moreno@example.com,1958-10-03T04:38:16.504Z,https://randomuser.me/api/portraits/women/78.jpg
2,Vicky Jimenez,female,Norwich,County Tyrone,vicky.jimenez@example.com,1992-04-29T09:55:00.294Z,https://randomuser.me/api/portraits/women/4.jpg
3,Kaan Laven,male,Ijzevoorde,Zuid-Holland,kaan.laven@example.com,1964-01-18T14:53:14.559Z,https://randomuser.me/api/portraits/men/99.jpg
4,Micky Wolters,male,Gellicum,Gelderland,micky.wolters@example.com,1950-07-31T01:45:14.027Z,https://randomuser.me/api/portraits/men/16.jpg
5,Albina Martinez,female,Forel (Lavaux),Genève,albina.martinez@example.com,1961-11-26T03:54:49.446Z,https://randomuser.me/api/portraits/women/76.jpg
6,Mason Mcdonalid,male,Boise,Hawaii,mason.mcdonalid@example.com,1995-03-23T08:33:58.956Z,https://randomuser.me/api/portraits/men/66.jpg
7,مهدیس گلشن,female,آمل,مازندران,mhdys.glshn@example.com,1987-10-29T23:23:34.174Z,https://randomuser.me/api/portraits/women/45.jpg
8,Debra Wilson,female,Kells,Carlow,debra.wilson@example.com,1953-05-27T21:41:22.976Z,https://randomuser.me/api/portraits/women/18.jpg
9,Mark Miles,male,Tweed,Tasmania,mark.miles@example.com,1955-02-07T05:37:18.982Z,https://randomuser.me/api/portraits/men/31.jpg

In [9]:
df1 = pd.DataFrame(get_users())

#### Now we have a pandas dataframe that can be used for any testing purposes that the tester might have.

### Example 2: Fruitvice API

##### We will use APIs through requests library

In [10]:
# import all the required libraries
import requests
import json

In [12]:
# Obtain the fruitvice API data using requests.get("url") function

data = requests.get("https://www.fruityvice.com/api/fruit/all")

In [13]:
# Retrieve results using json.loads() function

results = json.loads(data.text)

In [14]:
# Convert our json data into pandas data frame

pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
3,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
4,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
5,Prunus,Cherry,9,Rosaceae,None,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
6,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
7,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
8,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
9,Vitis,Grapes,47,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
10,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
11,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
12,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
13,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
14,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
15,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
16,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
17,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
18,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
19,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
20,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
21,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
22,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
23,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
24,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
25,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
26,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
27,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
28,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
29,Spondias,Umbu,73,Anacardiaceae,0,"{'carbohydrates': 0, 'protein': 0, 'fat': 0, '..."
30,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized

In [16]:
df2 = pd.json_normalize(results)

In [17]:
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
3,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
4,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
5,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
6,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
7,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
8,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
9,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
10,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
11,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
12,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
13,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
14,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
15,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
16,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
17,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
18,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
19,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
20,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
21,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
22,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
23,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
24,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
25,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
26,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
27,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
28,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
29,Spondias,Umbu,73,Anacardiaceae,0,0.00,0.00,0.00,0,0.00
30,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

In [18]:
df2.describe()

,id,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,39.258065,11.852258,0.781613,0.471613,52.677419,7.885161
std,25.583807,6.155615,0.595719,0.924248,28.442207,5.051239
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,16.500000,8.150000,0.400000,0.140000,32.000000,4.450000
50%,41.000000,11.400000,0.800000,0.300000,50.000000,8.000000
75%,65.500000,15.000000,1.000000,0.400000,67.000000,10.150000
max,73.000000,27.100000,2.600000,5.300000,147.000000,18.000000

In [19]:
# Extract some information from this dataframe about family and genus of a cherry.

cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

In [21]:
# Find out how many calories are contained in a banana.

cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

In [22]:
# Find out how much sugar is contained in a fig.

sug_fig = df2.loc[df2["name"]== 'Fig']
sug_fig.iloc[0]['nutritions.sugar']

16.0

#### Exercise
Load/extract information from free public APIs

In [31]:
data2 = requests.get('https://api.punkapi.com/v2/beers')

In [32]:
results1 = json.loads(data2.text)

In [33]:
df3 = pd.DataFrame(results1)
df3

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,...,srm,ph,attenuation_level,volume,boil_volume,method,ingredients,food_pairing,brewers_tips,contributed_by
0,1,Buzz,A Real Bitter Experience.,09/2007,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.50,60.0,1010,1044.0,...,10.0,4.4,75.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 64, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Spicy chicken tikka masala, Grilled chicken q...",The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.10,41.5,1010,1041.7,...,15.0,4.4,76.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 69, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Fresh crab with lemon, Garlic butter dipping ...",Be careful not to collect too much wort from t...,Sam Mason <samjbmason>
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.20,8.0,1007,1040.0,...,4.0,3.2,83.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 60, 'unit': ...","{'malt': [{'name': 'Propino Pale Malt', 'amoun...","[Smoked chicken wings, Miso ramen, Yuzu cheese...",Clean everything twice. All you want is the cl...,Sam Mason <samjbmason>
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.30,55.0,1012,1060.0,...,15.0,4.4,80.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Spicy crab cakes, Spicy cucumber and carrot T...",Play around with the fermentation temperature ...,Ali Skinner <AliSkinner>
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.20,59.0,1027,1069.0,...,5.0,4.4,67.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 66, 'unit': ...","{'malt': [{'name': 'Lager Malt', 'amount': {'v...","[Vietnamese squid salad, Chargrilled corn on t...",Make sure you have a big enough yeast starter ...,Sam Mason <samjbmason>
5,6,Electric India,Vibrant Hoppy Saison.,05/2013,"Re-brewed as a spring seasonal, this beer – wh...",https://images.punkapi.com/v2/6.png,5.20,38.0,1005,1045.0,...,7.5,4.4,88.9,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Mussels with a garlic and herb sauce, Crab me...",Source some really good heather honey to get t...,Sam Mason <samjbmason>
6,7,AB:12,Imperial Black Belgian Ale.,07/2012,An Imperial Black Belgian Ale aged in old Inve...,https://images.punkapi.com/v2/7.png,11.20,35.0,1017,1108.0,...,40.0,5.3,84.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 69, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Tandoori lamb with pomegranate, Beef Wellingt...",Don't worry too much about controlling the tem...,Sam Mason <samjbmason>
7,8,Fake Lager,Bohemian Pilsner.,03/2013,Fake is the new black. Fake is where it is at....,https://images.punkapi.com/v2/8.png,4.70,40.0,1010,1046.0,...,6.0,4.4,78.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Fried crab cakes with avocado salsa, Spicy sh...",Once the primary fermentation is complete get ...,Sam Mason <samjbmason>
8,9,AB:07,Whisky Cask-Aged Scotch Ale.,03/2010,Whisky cask-aged imperial scotch ale. Beer per...,https://images.punkapi.com/v2/9.png,12.50,30.0,1020,1106.0,...,42.0,5.6,83.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Munich', 'amount': {'value...","[Kedgeree, Scotch broth with sourdough bread, ...",Authentic heather honey adds a beautiful flora...,Sam Mason <samjbmason>
9,10,Bramling X,Single Hop IPA Series - 2011.,01/2011,"Good old Bramling Cross is elegant, refined, a...",https://images.punkapi.com/v2/10.png,7.50,75.0,1013,1068.0,...,11.0,4.4,80.9,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Warm blackberry pie, Vinegar doused fish and ...",Getting good Bramling Cross is key. Most Engli...,Sam Mason <samjbmason>
10,11,Misspent Youth,Milk & Honey Scotch Ale.,04/2013,"The brainchild of our small batch brewer, Geor...",https://images.punkapi.com/v2/keg.png,7.30,30.0,1020,1079.0,...,60.0,4.4,74.7,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 67, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...",[Roasted garlic and chilli infused camembert c...,"Lots of malt in this one. Mash-in in stages, a...",Sam Mason <samjbmason>
11,12,Arcade Nation,Seasonal Black IPA.,12/2015,Running the knife-edge between an India Pale A...,https://images.punkapi.com/v2/12.png,5.30,60.0,1012,1052.0,...,100.0,4.2,77.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...","[King prawn kebabs, Halibut with a mango and t...",Be as accurate as possible when weighing out y...,Sam Mason <samjbmason>
12,13,Movember,Moustache-Worthy Beer.,11/2009,"A deliciously robust, black malted beer with a...",https://images.punkapi.com/v2/13.png,4.50,50.0,1012,1047.0,...,70.0,5.2,74.5,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 68, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Vegetable egg scramble, Margherita pizza, Fre...","If you can’t find really fresh cascade, substi...",Sam Mason <samjbmason>
13,14,Alpha Dog,Existential Red Ale.,02/2010,A fusion of caramel malt flavours and punchy N...,https://images.punkapi.com/v2/14.png,4.50,42.0,1025,1046.0,...,31.0,4.4,72.8,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Pastrami, Swiss and horseradish sandwich, Sha...",Crush the malt as close to brewing time as pos...,Sam Mason <samjbmason>
14,15,Mixtape 8,"An Epic Fusion Of Old Belgian, American New Wa...",01/2012,This recipe is for the Belgian Tripel base. A ...,https://images.punkapi.com/v2/15.png,14.50,50.0,1014,1093.0,...,20.0,4.4,85.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale - Tipple', 'amoun...","[Coriander & chilli crab cakes, Goats cheese s...",Brew twice as much Belgian Tripel as you were ...,Sam Mason <samjbmason>
15,16,Libertine Porter,Dry-Hopped Aggressive Porter.,01/2012,An avalanche of cross-continental hop varietie...,https://images.punkapi.com/v2/16.png,6.10,45.0,1020,1067.0,...,109.5,4.4,70.1,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 68, 'unit': ...",{'malt': [{'name': 'Extra Pale - Spring Blend'...,"[Blue cheese beef burger, Glazed short ribs, C...",Mash in at a higher temperature to leave more ...,Sam Mason <samjbmason>
16,17,AB:06,Imperial Black IPA.,04/2011,"Our sixth Abstrakt, this imperial black IPA co...",https://images.punkapi.com/v2/17.png,11.20,150.0,1013,1098.0,...,35.0,NaN,87.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...","[Coffee dusted venison loin, Memphis-style bee...",Boil down to desired OG (about 17 litres).,Sam Mason <samjbmason>
17,18,Russian Doll – India Pale Ale,Nesting Hop Bomb.,08/2014,The levels of hops vary throughout the range. ...,https://images.punkapi.com/v2/18.png,6.00,70.0,1012,1058.0,...,12.5,5.2,79.3,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Spicy chicken skewers, Fish tacos with hot sa...",Create balance through experimentation with th...,Sam Mason <samjbmason>
18,19,Hello My Name Is Mette-Marit,Lingonberry Double IPA.,06/2013,We sent this beer to Norway where it was known...,https://images.punkapi.com/v2/19.png,8.20,70.0,1013,1076.0,...,NaN,4.4,83.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 66, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Fårikål (mutton stew) with a spicy twist, F...",Using crushed cranberries will dry out the bee...,Sam Mason <samjbmason>
19,20,Rabiator,Imperial Wheat Beer,03/2011,Imperial Wheat beer / Weizenbock brewed by a h...,https://images.punkapi.com/v2/keg.png,10.27,26.0,1014,1092.0,...,12.0,4.4,85.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 64, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Grilled portabello mushroom burger, Chicken s...",If you are struggling to get that authentic he...,Sam Mason <samjbmason>
20,21,Vice Bier,Hoppy Wheat Bier.,04/2013,Our take on the classic German Kristallweizen....,https://images.punkapi.com/v2/keg.png,4.30,25.0,1010,1043.0,...,15.0,4.0,81.8,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Citrus salad with balsamic dressing, Lobster,...",Ferment at higher or lower temperatures to sel...,Sam Mason <samjbmason>
21,22,Devine Rebel (w/ Mikkeller),Oak-aged Barley Wine.,12/2008,"Two of Europe's most experimental, boundary-pu...",https://images.punkapi.com/v2/22.png,12.50,100.0,1030,1093.0,...,18.0,4.4,68.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Stilton on gingerbread biscuits, Pot roasted ...",Rack off to a secondary fermenter before pitch...,Sam Mason <samjbmason>
22,23,Storm,Islay Whisky Aged IPA.,12/2007,Dark and powerful Islay magic infuses this tro...,https://images.punkapi.com/v2/23.png,8.00,60.0,1010,1082.0,...,6.0,4.4,86.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Oysters, Hickory smoked ham, Rocky Road]","After primary fermentation is complete, rack o...",Sam Mason <samjbmason>
23,24,The End Of History,The World's Strongest Beer.,06/2011,The End of History: The name derives from the ...,https://images.punkapi.com/v2/24.png,55.00,NaN,1000,1112.0,...,NaN,4.4,100.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Roasted wood pigeon with black pudding, Pan s...",You'll have to get this one all the way down t...,Sam Mason <samjbmason>
24,25,Bad Pixie,Spiced Wheat Beer.,10/2008,"2008 Prototype beer, a 4.7% wheat ale with cru...",https://images.punkapi.com/v2/25.png,4.70,45.0,1010,1047.0,...,4.0,4.4,79.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 67, 'unit': ...","{'malt': [{'name': 'Wheat', 'amount': {'value'...","[Poached sole fillet with capers, Summer fruit...",Make sure you have plenty of room in the ferme...,Sam Mason <samjbmason>

In [34]:
df3.describe()

,id,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level
count,25.000000,25.000000,24.00000,25.000000,25.000000,23.000000,23.000000,24.000000,25.000000
mean,13.000000,9.190800,52.68750,1013.840000,1068.508000,55.739130,28.195652,4.479167,79.960000
std,7.359801,10.022584,28.42068,6.780364,23.768185,60.471795,30.046078,0.467165,7.181864
min,1.000000,4.100000,8.00000,1000.000000,1040.000000,8.000000,4.000000,3.200000,67.000000
25%,7.000000,4.700000,37.25000,1010.000000,1046.000000,15.000000,8.750000,4.400000,75.000000
50%,13.000000,6.300000,47.50000,1012.000000,1067.000000,30.000000,15.000000,4.400000,80.000000
75%,19.000000,10.270000,60.00000,1017.000000,1092.000000,75.000000,37.500000,4.400000,84.000000
max,25.000000,55.000000,150.00000,1030.000000,1112.000000,219.000000,109.500000,5.600000,100.000000